repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  -  id: check-symlinks
  -  id: check-toml
  -  id: check-json
  -  id: check-yaml
  -  id: check-merge-conflict  # checks for files that contain merge conflict strings
  -  id: end-of-file-fixer
  -  id: check-added-large-files
     args: ['--maxkb=5120']
  -  id: trailing-whitespace
  -  id: detect-private-key
  -  id: check-ast  # checks whether the files parse as valid python
  -  id: debug-statements
  -  id: file-contents-sorter
     files: requirements.txt
- repo: https://github.com/asottile/pyupgrade
  rev: v2.32.1
  hooks:
  -  id: pyupgrade  # upgrades syntax for newer versions
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
    - id: python-use-type-annotations  # use typehints instead of type comments
    - id: python-no-eval  # security check for no eval() function calls
    - id: python-no-log-warn  # check for deprecated logger.warn method
    - id: python-check-blanket-noqa  # enforce `# noqa` comments have specific codes
    - id: python-check-blanket-type-ignore
- repo: https://github.com/asottile/yesqa
  rev: v1.3.0
  hooks:
  -   id: yesqa  # removes unnecessary `# noqa` comments
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files", "--line-length", "120"]
- repo: https://github.com/psf/black
  rev: 22.3.0  # https://github.com/psf/black/issues/2964#issuecomment-1080974737
  hooks:
  - id: black
    args:
      - "-S"
      - "--line-length"
      - "120"
- repo: https://github.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    args:
      # making compatible with black
      - "--max-line-length=120"
      - "--extend-ignore=E203,E501" # allow whitespace before ':'; allow line too long
- repo: https://github.com/asottile/dead
  rev: v1.5.0
  hooks:
  - id: dead  # detects dead python code such as unused variables/functions
    stages: [manual]  # $ pre-commit run --hook-stage manual
